ANALYTICS-3631 | Document LIPS Events API
GannettDigital/api-docs pull request #179
Opened 2021-08-24 15:07 UTC by clarkbremer

2021-08-24 18:39 UTC, brianroth-rl requested changes
While this is internal documentation, you should temporarily add it to the index.md file to verify that it renders properly.  It has strange rendering now that you probably would fix.

2021-08-24 18:39 UTC, brianroth-rl commented on source/includes/_lips_events.md
> +| GET `index` | /contacts/#id/events? |
The ? at the end of the events route should be removed.  It's not part of the route

2021-08-24 18:39 UTC, brianroth-rl commented on source/includes/_lips_events.md
> +##### Event Object:
A blank line is needed after this line so that the subsequent table renders

2021-08-24 18:39 UTC, brianroth-rl commented on source/includes/_lips_events.md
> +| Field Name | Datatype | Description |
A blank line is needed after this line so that the subsequent table renders

2021-08-24 18:39 UTC, brianroth-rl commented on source/includes/_lips_events.md
> +| Field Name | Datatype | Description |
A blank line is needed after this line so that the subsequent table renders

2021-08-24 18:39 UTC, brianroth-rl commented on source/includes/_lips_events.md
> +| Field Name | Datatype | Description |
A blank line is needed after this line so that the subsequent table renders

2021-08-24 18:39 UTC, brianroth-rl commented on source/includes/_lips_events.md
> +If `event_type` is ChatEvent, the following fields are also returned:
A blank line is needed after this line so that the subsequent table renders

2021-08-24 21:20 UTC, brianroth-rl approved these changes

2021-09-13 21:14 UTC, neelohitha approved these changes

2021-09-13 21:14 UTC, merged