ANALYTICS-4467 | available_zip_codes_api
GannettDigital/api-docs pull request #300
Opened 2022-10-06 11:23 UTC by martin-hristov-acc

**References**: [ANALYTICS-4467](https://jira.gannett.com/browse/ANALYTICS-4467)

**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1673

**Description**:
We need to add a zip codes api based on the new zip codes geofences table.

2022-10-06 15:21 UTC, NBnfork requested changes

2022-10-06 15:21 UTC, NBnfork commented on source/includes/_zip_codes.md
> +            "5555-1234",
These should be five digit zipcodes like `54194`

2022-10-06 15:21 UTC, NBnfork commented on source/includes/_zip_codes.md
> +Use GET to retrieve zip code. Data can be returned for a GMAID for a specific date range determined by start_date and end_date. Data is an array with all zip codes for, which have at least one walk i
Let's give this more context. This is a 5-digit zipcode that can be used in a zipcode filters in the `target_geofence` and `conversion_zone_geofence` report requests.

2022-10-12 14:23 UTC, brianroth-rl approved these changes

2022-10-19 13:37 UTC, NBnfork approved these changes

2022-10-19 14:15 UTC, merged