initial commit
GannettDigital/api-docs pull request #386
Opened 2024-08-27 12:32 UTC by martin-hristov-acc

**References**: [EDGE-10056](https://jira.gannett.com/browse/EDGE-10056)

**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1966

**Description**:
A new API for daily campaign activities

2024-08-27 13:49 UTC, brianroth-rl requested changes

2024-08-27 13:49 UTC, brianroth-rl commented on source/includes/_daily_campaign_activity.md
> +curl -g -H "Authorization: Bearer Bearer OAUTH_ACCESS_TOKEN \
This looks like a typo
```
Authorization: Bearer Bearer OAUTH_ACCESS_TOKEN \
```
Most likely this was copied from somewhere else, so I suspect it's incorrect there also.

2024-08-27 13:49 UTC, brianroth-rl commented on source/includes/_daily_campaign_activity.md
> +|bussiness_name|String|Business name|
typo

2024-08-27 13:49 UTC, brianroth-rl commented on source/includes/_daily_campaign_activity.md
> +|campaign_cycle|Restrict results to a single campaign cycle|
Is this necessary, we don't call out cycles in the response so allowing this as a filter doesn't seem like something we want.

2024-08-27 13:51 UTC, brianroth-rl commented on source/includes/_daily_campaign_activity.md
> +|campaign_cycle|Restrict results to a single campaign cycle|
[It's not supported and should be removed](https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1966/files#diff-f6bde42362fb05021213f3d538f637db596738a5a6c19df9e3af1d974468ae1bR1-R9)

2024-08-27 14:15 UTC, brianroth-rl approved these changes

2024-08-27 14:36 UTC, brianroth-rl approved these changes

2024-09-24 21:08 UTC, briannelson commented
Can this be merged please?

2024-10-03 15:47 UTC, merged